### ISSUE TITLE
Inquiry post

### ISSUE THREAD

**Issue by zorozip** [Matt2371/PINN_navier_stokes#1]
What do the suffixes of your model parameter pt. file represent?

**Comment by Matt2371** [comment]
"model{1 or 2}\_{# of neural network layers}l\_{hidden size of each layer}h_{# epochs trained}e\_{frac of training data selected}d.pt"

Model 1 is the implementation in Raissi 2019, Model 2 is my own implementation using the equations in the readme file.

**Comment by zorozip** [comment]
Thank you for your answer. What is the specific purpose of the time step sampling part?

**Comment by Matt2371** [comment]
The flow is unsteady, so sampling across time will help the model predict the correct time evolution. You could modify the experiment so that the time evolution is only governed by the PDE, but I don't plan on trying that for now.
